services:
  db: 
    image: postgres:16.1
    ports: 
     - 5442:5432
    volumes:
     - ./postgresql:/var/lib/postgresql/data
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: f1_db