name: Test on push

on: 
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps: 
      #copies project files
      - uses: actions/checkout@v4
      - name: Setup Python
      #sets up python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.1
          architecture: x64
          
      - name: Install dep
      - run: pip install dtaidistance fastf1 apache-airflow pytest pytest-mock pandas pyarrow

      - name: Test dags
      - run: pytest

